import type { Metadata } from "next";
import Link from "next/link";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  articles,
  users,
}: {
  children: ReactNode;
  articles: ReactNode;
  users: ReactNode;
}) {
  return (
    <>
      <nav>
        <Link href="/student-dashboard">Student Dashboard</Link> <br/>
        <Link href="/student-dashboard/settings">Settings</Link>
      </nav>
      {children}
      {users}
      {articles}
    </>
  );
}
